
muni_adj = {
    'Adjuntas':{'Yauco', 'Guayanilla', 'Peñuelas', 'Utuado', 'Lares', 'Ponce'},
    'Aguada':{'Aguadilla', 'Moca', 'Añasco', 'Rincón'},
    'Aguadilla':{'Aguada', 'Moca', 'Isabela'},
    'Aguas Buenas':{'Cidra', 'Bayamón', 'Guaynabo', 'San Juan', 'Comerío', 'Caguas'},
    'Aibonito':{'Salinas', 'Barranquitas', 'Coamo', 'Cidra', 'Cayey'},
    'Añasco':{'Aguada', 'Las Marías', 'Mayagüez', 'Rincón', 'Moca', 'San Sebastián'},
    'Arecibo':{'Utuado', 'Ciales', 'Hatillo', 'Barceloneta', 'Florida'},
    'Arroyo': {'Guayama', 'Patillas'},
    'Barceloneta':{'Florida', 'Arecibo', 'Manatí'},
    'Barranquitas': {'Corozal', 'Naranjito', 'Coamo', 'Aibonito', 'Comerío', 'Cidra', 'Orocovis'},
    'Bayamón':{'Aguas Buenas', 'Comerío', 'Toa Baja', 'Cataño', 'Guaynabo', 'Toa Alta', 'Naranjito'},
    'Cabo Rojo':{'Hormigueros', 'Lajas', 'San Germán', 'Mayagüez'},
    'Caguas':{'San Juan', 'Trujillo Alto', 'Aguas Buenas', 'Cidra', 'Cayey', 'San Lorenzo', 'Gurabo'},
    'Camuy':{'Lares', 'San Sebastián', 'Quebradillas', 'Hatillo'},
    'Canóvanas':{'Juncos', 'Las Piedras', 'Loíza', 'Carolina', 'Río Grande'},
    'Carolina':{'San Juan', 'Trujillo Alto', 'Gurabo', 'Juncos', 'Canóvanas', 'Loíza'},
    'Cataño':{'San Juan', 'Bayamón', 'Guaynabo', 'Toa Baja', 'Guaynabo'},
    'Cayey': {'Salinas', 'Guayama', 'Cidra', 'Caguas', 'Aibonito', 'Salinas', 'San Lorenzo'},
    'Ceiba': {'Fajardo', 'Naguabo', 'Río Grande'},
    'Ciales': {'Orocovis', 'Florida', 'Manatí'},
    'Cidra': {'Cayey', 'Comerío', 'Aguas Buenas', 'Aibonito', 'Barranquitas', 'Caguas'},
    'Coamo':{'Santa Isabel', 'Orocovis', 'Barranquitas', 'Villalba', 'Juana Díaz', 'Aibonito', 'Salinas'},
    'Comerío':{'Naranjito', 'Bayamón', 'Barranquitas', 'Cidra', 'Aguas Buenas'},
    'Corozal': {'Orocovis', 'Barranquitas', 'Vega Alta', 'Toa Alta', 'Morovis', 'Naranjito'},
    'Culebra':{},
    'Dorado': {'Toa Alta', 'Vega Alta', 'Toa Baja'},
    'Fajardo':{'Ceiba', 'Luquillo'},
    'Florida': {'Ciales', 'Barceloneta', 'Arecibo', 'Manatí'},
    'Guánica': {'Sabana Grande', 'Lajas', 'Yauco'},
    'Guayama': {'Cayey', 'Salinas', 'Patillas', 'Arroyo'},
    'Guayanilla':{'Adjuntas', 'Yauco', 'Peñuelas'},
    'Guaynabo': {'Aguas Buenas', 'Cataño', 'Bayamón', 'San Juan'},
    'Gurabo':{'San Lorenzo', 'Trujillo Alto', 'Caguas', 'Carolina', 'Juncos'},
    'Hatillo': {'Lares', 'Utuado', 'Camuy', 'Arecibo'},
    'Hormigueros':{'Cabo Rojo', 'San Germán', 'Mayagüez'},
    'Humacao':{'Yabucoa', 'Naguabo', 'Las Piedras'},
    'Isabela':{'San Sebastián', 'Quebradillas', 'Aguadilla', 'Moca'},
    'Jayuya': {'Ponce', 'Utuado', 'Ciales'},
    'Juana Díaz': {'Jayuya', 'Ciales', 'Orocovis', 'Villalba', 'Ponce', 'Coamo', 'Santa Isabel'},
    'Juncos':{'Canóvanas', 'Carolina', 'Gurabo', 'San Lorenzo', 'Las Piedras'},
    'Lajas':{'San Germán', 'Sabana Grande', 'Cabo Rojo', 'Guánica'},
    'Lares': {'Maricao', 'Yauco', 'Camuy', 'San Sebastián', 'Las Marías', 'Hatillo', 'Utuado', 'Adjuntas'},
    'Las Marías': {'Maricao', 'Añasco', 'San Sebastián', 'Mayagüez', 'Lares'},
    'Las Piedras': {'Yabucoa', 'Canóvanas', 'Río Grande', 'Juncos', 'San Lorenzo', 'Naguabo', 'Humacao'},
    'Loíza':{'Canóvanas', 'Carolina', 'Río Grande'},
    'Luquillo':{'Fajardo', 'Río Grande'},
    'Manatí':{'Morovis', 'Ciales', 'Florida', 'Barceloneta', 'Vega Baja'},
    'Maricao': {'San Germán', 'Sabana Grande', 'Yauco', 'Las Marías', 'Lares', 'Mayagüez', 'Adjuntas'},
    'Maunabo': {'Patillas', 'Yabucoa'},
    'Mayagüez':{'Añasco', 'Hormigueros', 'San Germán', 'Maricao', 'Las Marías', 'Cabo Rojo'},
    'Moca':{'Aguada', 'Aguadilla', 'Añasco', 'Isabela', 'San Sebastián'},
    'Morovis': {'Orocovis', 'Manatí', 'Vega Baja', 'Vega Alta', 'Ciales', 'Corozal'},
    'Naguabo': {'Humacao', 'Río Grande', 'Ceiba', 'Las Piedras'},
    'Naranjito': {'Toa Alta', 'Barranquitas', 'Comerío', 'Corozal', 'Bayamón'},
    'Orocovis':{'Villalba', 'Coamo', 'Morovis', 'Corozal', 'Ciales', 'Jayuya', 'Barranquitas'},
    'Patillas':{'San Lorenzo', 'Yabucoa', 'Maunabo', 'Guayama', 'Arroyo'},
    'Peñuelas': {'Adjuntas', 'Guayanilla', 'Ponce'},
    'Ponce': {'Adjuntas', 'Utuado', 'Jayuya', 'Peñuelas', 'Juana Díaz'},
    'Quebradillas': {'San Sebastián', 'Isabela', 'Camuy'},
    'Rincón':{'Añasco', 'Aguada'},
    'Río Grande': {'Las Piedras', 'Naguabo', 'Ceiba', 'Loíza', 'Canóvanas', 'Luquillo'},
    'Sabana Grande':{'Lajas', 'Guánica', 'Maricao', 'San Germán', 'Yauco'},
    'Salinas': {'Aibonito', 'Cayey', 'Coamo', 'Santa Isabel', 'Guayama'},
    'San Germán':{'Mayagüez', 'Maricao', 'Lajas', 'Hormigueros', 'Cabo Rojo', 'Sabana Grande'},
    'San Juan': {'Caguas', 'Trujillo Alto', 'Guaynabo', 'Carolina'},
    'San Lorenzo':{'Patillas', 'Yabucoa', 'Gurabo', 'Caguas', 'Cayey', 'Juncos', 'Las Piedras'},
    'San Sebastián':{'Isabela', 'Quebradillas', 'Camuy', 'Las Marías', 'Añasco', 'Moca', 'Lares'},
    'Santa Isabel': {'Coamo', 'Juana Díaz', 'Salinas'},
    'Toa Alta': {'Naranjito', 'Dorado', 'Toa Baja', 'Vega Alta', 'Corozal', 'Bayamón'},
    'Toa Baja': {'Toa Alta', 'Bayamón', 'Dorado', 'Cataño'},
    'Trujillo Alto': {'Caguas', 'Gurabo', 'San Juan', 'Carolina'},
    'Utuado':{'Adjuntas', 'Ponce', 'Hatillo', 'Arecibo', 'Lares', 'Ciales', 'Jayuya'},
    'Vega Alta': {'Morovis', 'Corozal', 'Dorado', 'Vega Baja'},
    'Vega Baja':{'Morovis', 'Manatí', 'Vega Alta'},
    'Vieques':{},
    'Villalba':{'Orocovis', 'Juana Díaz', 'Coamo'},
    'Yabucoa':{'Maunabo', 'San Lorenzo', 'Las Piedras', 'Humacao', 'Patillas'},
    'Yauco':{'Maricao', 'Lares', 'Adjuntas', 'Sabana Grande', 'Guánica', 'Guayanilla'}
    }
